### ISSUE TITLE
Error in bash.nanorc: Command "header" not understood

### ISSUE THREAD

**Issue by Polyergic** [serialhex/nano-highlight#17]
In Mac OS X Yosemite 10.10.2, using Apple's nano 2.0.6 (but not MacPorts' nano 2.2.6), including bash.nanorc yields this error:

    Error in /Users/polyergic/.nano/bash.nanorc on line 2: Command "header" not understood

**Comment by serialhex** [comment]
This seems to be a similar error as here: https://github.com/scopatz/nanorc/issues/17 you can either update nano, or comment out that line, your choice.  Sorry for the delay in replying, little access to the interwebz will do that...

**Comment by Polyergic** [comment]
Looks like that is a different case of the same error.  I can't update the nano that Apple ships; it sounds like the conclusion is that Apple's nano is not supported.

I don't know what the "header" command does, so I don't know what effect to expect from commenting it out - for all I know that would break the rest of the file.  Since you suggest that as a workaround, I'm assuming it just disables some unsupported feature.

**Comment by serialhex** [comment]
Disabling an unsupported feature is all it does.  Later versions of nano support the header command, unfortunately yours does not & breaks nano when you include it in the .rc file.  If you comment it out and you still have the same problem let me know.

**Comment by mercury00** [comment]
By the way, if you're using this on Apple, it won't really work until you do like so:

sed -i -e 's|\\<|[[:<:]]|g;s|\\>|[[:>:]]|g'  /path/to/nano/files/*

the bsd systems regex doesn't understand the (\< and \>) syntax, and all instances of it have to be replaced by  ([[:<:]] and  [[:>:]]). FYI.

**Comment by Polyergic** [comment]
@mercury00, is that just for Apple's nano, or does it affect Macports nano?  Will non-Apple nano work correctly with the substitutions?

**Comment by mercury00** [comment]
They seem to be mutually exclusive; the bsd regex and the linux/gnu regex have a different syntax. I don't know if macports installs its own regex, so someone would have to test it.

I'm trying to incorporate this project's code into the other nanorc project that builds the files for you on your system, using a standardized template, which might already handle testing the regex.

**Comment by serialhex** [comment]
@mercury00 I know one of the other nano-highlight projects I found here on GitHub builds it from templates & does the checking.  I was thinking of doing that myself with these, but figured it might be nicer to have a drop-in solution for the lazy (like myself! :-D ) Though having uniform coloring (or being able to change your scheme) might be nice...

**Comment by Polyergic** [comment]
@mercury00, I've been using this with Macports nano without the substitutions and not noticed a problem.  What should I test?

**Comment by mercury00** [comment]
If it doesn't complain about syntax errors, it's probably working, which implies macports uses gnu regex, so that's pretty much all the testing needed.

**Comment by Polyergic** [comment]
Just tried opening a few files in both `/usr/bin/nano` and `/opt/local/bin/nano`.  `/usr/bin/nano` only complains about the "header" in `bash.nanorc`, it does not complain about any other syntax, but it also does not use all of the colors used by `/opt/local/bin/nano`.  So some of it still works, and most of what doesn't work also doesn't generate errors.  Time to update my answer at http://stackoverflow.com/questions/27971343/editing-nanorc-on-osx-v10-9-5 .

**Comment by emmanuj** [comment]
For mac users, you can simply use brew to install the GNU nano. This resolved the issue for me no other config or workaround needed afterwards.
