### ISSUE TITLE
Additional .nanorc files

### ISSUE THREAD

**Issue by skwerlman** [serialhex/nano-highlight#19]
I'm not sure if you're aware of these or not, but there're a few highlighters in this repo that you're missing: https://github.com/nanorc/nanorc

All it's files are public domain, but the old maintainer used `make` to keep the files clean, so it might be awkward to integrate them here.

**Comment by serialhex** [comment]
I've seen that repo before, but thanks for the heads-up.  My internet is kind of spotty at the moment so updating *anything* is a pain... but maybe soon I'll be able to update! :-D
