### ISSUE TITLE
Support for OpenDocument's XML

### ISSUE THREAD

**Issue by rautamiekka** [serialhex/nano-highlight#20]
OpenDocument Format (ODF) is fully Open Source standard based on XML, so you can find everything on Google.

The most commonly used files start with OD and then a letter that tells what file it is. They're regular ZIP files with a bunch of files inside, of which most are pure XML text with its own syntax.

Then there are uncompressed XML files which contain everything inside, thus the file is many times bigger. The extension starts with FOD and a letter, same as the ZIPped ones.

Those Flat OpenDocument files' `content.xml` inside files are ones I want support for.

There are 3 ODS and 1 FODS file (compressed with 7-Zip 15.06 Beta x64, using LZMA2 with 64MB dictionary size, so you can decompress under 32-bit OS. You need at least `xz-utils` v5.1.1alpha under Linux, but 7-Zip functions perfectly under Wine) at https://drive.google.com/folderview?id=0ByxhMpKDhtkMS2dWS3dLUFk3Q1U you can use for testing the highlighting. All of those are publicly available, so feel free to make use of them.

Also, https://drive.google.com/folderview?id=0B6Z3ucpyN1X2WmVtTnE0ZHJfb2s has a big load of templates for all components in LibreOffice.

**Comment by serialhex** [comment]
Wow, I must have totally spaced & not seen this, sorry about that!  Unfortunately I don't have the time, nor incentive to add this capability.  To make a nano syntax highlighter isn't too difficult, the syntax can be found here: www.nano-editor.org/dist/v2.1/nanorc.5.html If you get it up & running, send me a pull request & I will gladly add your contribution!
