### ISSUE TITLE
todo.nanorc errors when loaded

### ISSUE THREAD

**Issue by Lindenk** [serialhex/nano-highlight#22]
When trying to include `todo.nanorc`, nano prints the error `Error in /path/to/.nano/todo.nanorc on line 1: A syntax name must be quoted`, followed by other errors caused by the first line not running correctly.

nano version:
```
 nano, version 2.6.1
 (C) 1999..2016 Free Software Foundation, Inc.
 (C) 2014..2016 the contributors to nano
 Email: nano@nano-editor.org	Web: https://nano-editor.org/
 Compiled options: --disable-wrapping-as-root --enable-utf8
```

I'm running arch linux x86 64-bit.

**Comment by serialhex** [comment]
Hey, the issue was simply that it had spaces in the name of the kind of highlighting.  I changed it & updated the repo.  I'm going to check for more like that but you should be able to pull & get the fix right now.  Thanks for bringing this to my attention!
