### ISSUE TITLE
sourceslist.nanorc bad regex

### ISSUE THREAD

**Issue by MuhsinFatih** [serialhex/nano-highlight#28]
Hello
Just cloned the repo and set all the highlightings. Nano throws me the following error for sourceslist.nanorc:

Error in /home/mufa/.nano/sourceslist.nanorc on line 4: Bad regex "^deb(-src)? ((http|file|ftp):/[^ ]+|cdrom:\[[^\]]+\]/|cdrom:\[[a-zA-Z0-9\._-\(\) ]+\]/) [^ ]+ .+$": Invalid range end

Error in /home/mufa/.nano/sourceslist.nanorc on line 6: Bad regex "^deb(-src)? ((http|file|ftp):/[^ ]+|cdrom:\[[^\]]+\]/|cdrom:\[[a-zA-Z0-9\._-\(\) ]+\]/) [^ ]+": Invalid range end

Error in /home/mufa/.nano/sourceslist.nanorc on line 11: Bad regex "cdrom:\[[a-zA-Z0-9\._-\(\) ]+\]/": Invalid range end

**Comment by serialhex** [comment]
Oohhh.... I'll have to take a look at this!  Might take a day or so though, kinda busy, but thank you for opening the issue!

**Comment by serialhex** [comment]
@MuhsinFatih I just updated the repo with a possible fix.  I'm not at home right now so I can't test, but it looks like a misplaced `-` in the regex, I fixed that and it should be fine now.  Pull & test and if it works then please close this issue!

Have an awesome day!!!

**Comment by MuhsinFatih** [comment]
Yep, no errors now 😄
